### ISSUE TITLE
Better icons for voting

### ISSUE THREAD

**Issue by alexomanie** [Undermyspell/cp-voting-tool#109]
find better icons for voting. The thumb up and down are confusing for people

**Comment by AlexSchoenfeld** [comment]
I would suggest something like a arrow up (like in feddit/reddit) or a "+1".

Also I find it pretty irritating that there is a orange thumbs down shown when I clicked on the thumbs up (because I can't really vote it down as the icon would tell, but only undo my thumbs up).

**Comment by alexomanie** [comment]
icon is replaced
