### ISSUE TITLE
Startup instructions

### ISSUE THREAD

**Issue by PeterIttner** [Undermyspell/cp-voting-tool#61]
Cloud you please at startup instructions in a readme file ("Getting Started"-chapter)
Also please add a docker-compose file, to quickly start the whole application (client & api) with minimal effort.
Thanks in advance!

**Comment by alexomanie** [comment]
Yes we can do it :) Thanks for the suggestion!

**Comment by Undermyspell** [comment]
@PeterIttner done, you can try out :)

**Comment by PeterIttner** [comment]
Works thank you
